# Generated by Django 3.0.4 on 2020-07-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOOK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descriprion', models.CharField(max_length=300)),
                ('Userid', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.registered')),
            ],
        ),
        migrations.CreateModel(
            name='closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemtype', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('Userid', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.registered')),
            ],
        ),
    ]
