# Generated by Django 3.0.4 on 2020-07-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0003_auto_20200719_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='look',
            name='Userid',
        ),
        migrations.DeleteModel(
            name='closet',
        ),
        migrations.DeleteModel(
            name='LOOK',
        ),
    ]
