# Generated by Django 3.0.4 on 2020-07-20 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outfits', '0004_auto_20200720_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOOK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=300)),
                ('lookImg', models.ImageField(default='outfits/images', upload_to='outfits/images')),
                ('Userid', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='closet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Itemtype', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('itemImg', models.ImageField(upload_to='outfits/images')),
                ('Userid', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
