# Generated by Django 3.0.4 on 2020-07-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='Fullname',
            new_name='Username',
        ),
    ]
