# Generated by Django 3.0.4 on 2020-07-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200719_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='stylist',
            field=models.BooleanField(default=False),
        ),
    ]
