# Generated by Django 3.0.4 on 2020-07-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200720_0305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registered',
        ),
    ]
